sudo: required

services:
  - docker

stages:
  - build
  - promote

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  - export TEMP_IMAGE="howtoadhd/travis-dump:howtoadhd_dev-services__${TRAVIS_COMMIT}"

jobs:
  include:

    - stage: build
      before_script:
        - docker pull alpine:3.6
      script:
        - docker build --no-cache -t builder:dev-services .
      after_success:
        - docker tag builder:dev-services ${TEMP_IMAGE}
        - docker push ${TEMP_IMAGE}

    - stage: promote
      before_script:
        - docker pull ${TEMP_IMAGE}
        - docker tag ${TEMP_IMAGE} builder:dev-services
      script:
        - |
          if [ $TRAVIS_PULL_REQUEST == 'false' ]; then
            docker tag builder:dev-services howtoadhd/dev-services:${TRAVIS_BRANCH};
            docker push howtoadhd/dev-services:${TRAVIS_BRANCH};
          fi
        - |
          if [ $TRAVIS_PULL_REQUEST == 'false' ] && [ $TRAVIS_BRANCH == 'master' ]; then
          	docker tag builder:dev-services howtoadhd/dev-services:latest;
          	docker push howtoadhd/dev-services:latest;
          fi

notifications:
  webhooks:
    urls:
      secure: "LZDhAwUtLME8C4cL9Fgf9c80CqLSh9haCok+fLo324Xn+9bAG2lq4Z1f6/Ivpg+Epg1A+v1URxWHGgJuid9GQxVWJ8mfZ6D9m5TlKND+7GjFNZZytZboSL6op+CEojbJJkJvW0fSQpResD5jBZbP+TEHE7Bga1yuMtPUkKtoT0cWoTVi7r/OVJ4tMUsuQA2/Aop3zLUzEOj6+ICzvaIF8J68pKDHZTsVP9bJst643hTWnnglhIHqSrERWYDvhdE18MMGWsz0b7vKfdD9dpHuo0sJlvOsXRRY0KAhun/WD/NLf1c88Dcy3uarq8Df0b9jorJlAgnULFvZg94ViAcny9Phwn/KAug+I21usflcNjzkbfoTDYy654I4jdbzMCw5IdJESH7JXrjKhUMzh7AvPYSbr5LCUsunXknSFRYB649YuxHDjDf5abo5KCpwkmXCxB54MFM/HFVsGSngYPEDUX9Ze+2X/XHwYpttSpxbJ+eQlAQHePA0IePjWUL6DmSVp/KbT2K28arKKN/pAZndb8AOIL3j0Ht17Um2wnt4RA3QpbZuAFxdgvLllHCvEmXk11KKdGs5v5j8NVYoy872hchb4yC2l5x+mZ29xfrpUBSl5N6oNWbGDOF5uIOuWfhJdB6jZxlrQ8ibC1qOX/DXo9lBeP0Ck4nAnBb4TMvhL9w="
